## Numpy

In [ ]:
import numpy as np # pip install numpy

In [ ]:
#dir(np)

In [ ]:
list(range(0,10)) # seq

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr_ran = np.arange(0,10,1) # (0,10)# 0 to 9
arr_ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr_ran)

numpy.ndarray

# how to check length of the array

- to count the number of elements within the array
- to count the total dimension of the data

In [ ]:
list(range(0,10))

In [ ]:
arr = np.array(range(1,10))
print("Length:",len(arr))
print("Size:",arr.size)

Length: 9
Size: 9


In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([range(1,10),range(1,10)])
print("Length:",len(arr))
print("Size:",arr.size)

Length: 2
Size: 18


In [ ]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

- np.array
- ndim
- size

In [ ]:
arr2d = np.array([
    [[1,2,3],[4,5,6]],
     [[5,6,7],[8,9,10]
]])
print(arr2d.size)

12


In [ ]:
arr2d.shape

(2, 2, 3)

In [ ]:
arr.ndim

2

## want to calculate the memory usage of the given array

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.size*arr.itemsize # 8 bytes

80

In [ ]:
arr.nbytes

80

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr_2d.ndim

2

In [ ]:
arr_2d.size

8

whenever you are working with Numpy or Torch or HuggingFace. Seed - value will make sure the data is uniform.

Training process. Multiple calculations:
np.dot(weights,data)

- in neural network, the initial weights are random. After training, the weights are updated.

In [ ]:
np.random.seed(42) # 0 or 42 or 123
# Kaggle competition = seed value

In [ ]:
np.array(range(1,10)) #9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
n_arr = np.random.rand(10) # size = 10 0 to 0.99

In [ ]:
n_arr

array([0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446])

In [ ]:
n_arr.size

10

In [ ]:
n_arr.ndim

1

In [ ]:
# re-shape

In [ ]:
n_arr

array([0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446])

In [ ]:
2*5
4*3=12
size = 10

In [ ]:
n_arr = n_arr.reshape(2,5) # n_arr.size

In [ ]:
n_arr.shape

(2, 5)

In [ ]:
n_arr

array([[0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998],
       [0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446]])

In [ ]:
n_arr.ndim

2

In [ ]:
n_arr.T

array([[0.12203823, 0.66252228],
       [0.49517691, 0.31171108],
       [0.03438852, 0.52006802],
       [0.9093204 , 0.54671028],
       [0.25877998, 0.18485446]])

In [ ]:
n_arr = n_arr.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
n_arr.shape

(5, 2)

In [ ]:
n_arr

array([[5.96779016e-01, 2.89634755e-02],
       [2.53093027e-01, 3.78034694e-05],
       [8.68393701e-02, 5.65683206e-01],
       [2.77907812e-01, 9.25557826e-01],
       [4.34545481e-01, 3.73025355e-01]])

In [ ]:
trans_n_arr = n_arr.T

In [ ]:
trans_n_arr.shape

(2, 5)

In [ ]:
trans_n_arr

array([[0.12203823, 0.03438852, 0.25877998, 0.31171108, 0.54671028],
       [0.49517691, 0.9093204 , 0.66252228, 0.52006802, 0.18485446]])

- dot (np.dot) # pairwise similarity = cosine
- seed (only when you are training the model)
- random (when working with AI - weights are basically randomly generated initially)
- transpose. it should the size of the original array
- array (numpy: type conversion)

In [ ]:
len(n_arr.shape) # len(1,2,3) = 3

2

In [ ]:
len(n_arr.shape) == n_arr.ndim

True

In [ ]:
n_arr.size

10

In [ ]:
arr_3d = np.array([[[1,2,3,4],[4,5,6,8]],[[1,7,8,9],[0,9,10,11]]])

In [ ]:
arr_3d.shape # 2x2x4

(2, 2, 4)

In [ ]:
width,height,channel = (1080,1920,3) # image
# range of colors 0 to 255
# 0 - black
# 255 - white
# RGB - channel- (255,0,0) # red
# 0,255,0 # green
# 123,0,185

# Mathematical operations using Numpy

np.dot(vector1,vector2)

[1,2,3]
[4,5,6]
4+10+18 = 32
np.dot()

In [ ]:
marks = [65,78,94,66,88,80,91,97,100]
marks = np.array(marks)
type(marks) #numpy.ndarray

# first rule of median
# sort [65,66,78,80,88,91,94,97,100]
# min and max

numpy.ndarray

In [ ]:
mean = np.mean(marks)
print(mean)

84.33333333333333


In [ ]:
sum(marks)/len(marks)

np.float64(84.33333333333333)

In [ ]:
median = np.median(marks)
print(median)

88.0


In [ ]:
variance = np.var(marks)
print(variance)

147.33333333333334


In [ ]:
np.sqrt(variance) # standard deviation

np.float64(12.138094304022083)

In [ ]:
std_deviation = np.std(marks) # normalize the given array
print(std_deviation)

12.138094304022083


In [ ]:
distibution = np.linspace(0,100,9) # distribution
distibution

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [ ]:
len(distibution)

9

In [ ]:
w = np.random.rand(2,3) #mxn = 2x3
x = np.random.rand(3,1) #mxn = 3x1
#matrix mul = 2x3,3x1 = 2,1
#lets see the dimension

In [ ]:
matrix_mul = np.matmul(w,x)

In [ ]:
matrix_mul.shape

(2, 1)

In [ ]:
dot_product = np.dot(w,x)

In [ ]:
dot_product.shape

(2, 1)

In [ ]:
import math
math.log10(10)

1.0

## NLTK

In [ ]:
import nltk #pip install nltk

In [ ]:
# this should be just one time process
nltk.download('punkt_tab')
nltk.download('wordnet') # wordnet - is mainly one of the dataset in the nltk package

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [ ]:
sample_text = "NLTK is a powerful library lowerd, for natural language processing in Python."

In [ ]:
sentences = sent_tokenize(sample_text)

In [ ]:
len(sentences)

1

In [ ]:
tokens = word_tokenize(sample_text)
len(tokens)

14

In [ ]:
from nltk.tokenize.treebank import TreebankWordTokenizer, TreebankWordDetokenizer

In [ ]:
s = "OpenAI tokenization lowerd."

In [ ]:
d = TreebankWordDetokenizer()
t = TreebankWordTokenizer()

In [ ]:
tokens = t.tokenize(s)

In [ ]:
tokens

['OpenAI', 'tokenization', 'lowerd', '.']

In [ ]:
d.detokenize(tokens) == s

True

### POS

In [ ]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [ ]:
from nltk import pos_tag # parts of speech tagging

In [ ]:
sentence = "The quick brown fox jumps over the lazy dog"
tokens = word_tokenize(sentence)

In [ ]:
len(tokens)

9

In [ ]:
tagged = pos_tag(tokens)
print(tagged)

[('The', 'DT'), ('quick', 'JJ'), ('brown', 'NN'), ('fox', 'NN'), ('jumps', 'VBZ'), ('over', 'IN'), ('the', 'DT'), ('lazy', 'JJ'), ('dog', 'NN')]


## Sentiment analysis

In [ ]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer

In [ ]:
sia = SentimentIntensityAnalyzer()
text = "this product has killed a customer"
print(sia.polarity_scores(text))

{'neg': 0.529, 'neu': 0.471, 'pos': 0.0, 'compound': -0.6705}


### Synonyms and Antonyms

In [ ]:
from nltk.corpus import wordnet

In [ ]:
word = "interest"
results = wordnet.synsets(word)

In [ ]:
synonyms = []
antonyms = []
for syn in results:
    for lemma in syn.lemmas():
        synonyms.append(lemma.name())
        if lemma.antonyms():
            antonyms.append(lemma.antonyms()[0].name())

In [ ]:
synonyms = set(synonyms)
antonyms = set(antonyms)

In [ ]:
synonyms

{'concern',
 'interest',
 'interest_group',
 'interestingness',
 'involvement',
 'matter_to',
 'occupy',
 'pastime',
 'pursuit',
 'sake',
 'stake',
 'worry'}

In [ ]:
antonyms

{'bore', 'uninterestingness'}

## POS Tagging and NER

In [ ]:
nltk.download('punkt_tab') # lemmatization
nltk.download("punkt")
nltk.download("averaged_perceptron_tagger")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
sentences = [
    "I am the hope of the universe",
    "I am going to be the King of the Pirates",
    "People’s lives don’t end when they die, it is when they lose faith",
    "I am the bone of my sword, and I have created over a thousand blades",
    "Fear is not evil, it tells you what your weakness is",
    "A lesson without pain is meaningless, and that is a truth of the world",
]

In [ ]:
for s in sentences:
    tokens = nltk.word_tokenize(s)
    pos_tags = nltk.pos_tag(tokens)
    print(pos_tags)
    # ner

[('I', 'PRP'), ('am', 'VBP'), ('the', 'DT'), ('hope', 'NN'), ('of', 'IN'), ('the', 'DT'), ('universe', 'NN')]
[('I', 'PRP'), ('am', 'VBP'), ('going', 'VBG'), ('to', 'TO'), ('be', 'VB'), ('the', 'DT'), ('King', 'NNP'), ('of', 'IN'), ('the', 'DT'), ('Pirates', 'NNS')]
[('People', 'NNS'), ('’', 'VBP'), ('s', 'JJ'), ('lives', 'NNS'), ('don', 'VBP'), ('’', 'JJ'), ('t', 'JJ'), ('end', 'NN'), ('when', 'WRB'), ('they', 'PRP'), ('die', 'VBP'), (',', ','), ('it', 'PRP'), ('is', 'VBZ'), ('when', 'WRB'), ('they', 'PRP'), ('lose', 'VBP'), ('faith', 'NN')]
[('I', 'PRP'), ('am', 'VBP'), ('the', 'DT'), ('bone', 'NN'), ('of', 'IN'), ('my', 'PRP$'), ('sword', 'NN'), (',', ','), ('and', 'CC'), ('I', 'PRP'), ('have', 'VBP'), ('created', 'VBN'), ('over', 'IN'), ('a', 'DT'), ('thousand', 'CD'), ('blades', 'NNS')]
[('Fear', 'NN'), ('is', 'VBZ'), ('not', 'RB'), ('evil', 'JJ'), (',', ','), ('it', 'PRP'), ('tells', 'VBZ'), ('you', 'PRP'), ('what', 'WP'), ('your', 'PRP$'), ('weakness', 'NN'), ('is', 'VBZ')]
[('A

In [ ]:
nltk.download("maxent_ne_chunker")
nltk.download("words")
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.


True

nltk:
- download.py #
- main.py # nltk.download()

In [ ]:
sentences = [
    "Barack Obama was born in Hawaii.",
    "Apple is looking at buying a United Kingdom startup.",
    "Elon Musk founded Vimal at India",
]

In [ ]:
for s in sentences:
    tokens = nltk.word_tokenize(s)
    pos_tags = nltk.pos_tag(tokens)
    chunks = nltk.ne_chunk(pos_tags)
    print(chunks)

(S
  (PERSON Barack/NNP)
  (PERSON Obama/NNP)
  was/VBD
  born/VBN
  in/IN
  (GPE Hawaii/NNP)
  ./.)
(S
  (GPE Apple/NNP)
  is/VBZ
  looking/VBG
  at/IN
  buying/VBG
  a/DT
  (GPE United/NNP Kingdom/NNP)
  startup/NN
  ./.)
(S
  (PERSON Elon/NNP)
  (PERSON Musk/NNP)
  founded/VBD
  (PERSON Vimal/NNP)
  at/IN
  (GPE India/NNP))


## Stopwords

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [ ]:
stop_words

In [ ]:
quotes = [
    "I am the hope of the universe",
    "I am going to be the King of the Pirates",
    "People’s lives don’t end when they die, it is when they lose faith",
    "I am the bone of my sword, and I have created over a thousand blades",
    "Fear is not evil, it tells you what your weakness is",
    "A lesson without pain is meaningless, and that is a truth of the world",
]

In [ ]:
for s in quotes:
    tokens = nltk.word_tokenize(s)
    filtered = [w for w in tokens if w.lower() not in stop_words] # list comprehension
    print("Original:", s)
    print("Filtered:", " ".join(filtered), "\n")

Original: I am the hope of the universe
Filtered: hope universe 

Original: I am going to be the King of the Pirates
Filtered: going King Pirates 

Original: People’s lives don’t end when they die, it is when they lose faith
Filtered: People ’ lives ’ end die , lose faith 

Original: I am the bone of my sword, and I have created over a thousand blades
Filtered: bone sword , created thousand blades 

Original: Fear is not evil, it tells you what your weakness is
Filtered: Fear evil , tells weakness 

Original: A lesson without pain is meaningless, and that is a truth of the world
Filtered: lesson without pain meaningless , truth world 



## Lemmatization and Stemming

### Stemming: Just cuts off prefixes/suffixes without caring about grammar.

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
words = ["playing", "played", "happily", "flies", "better", "best","running","runs"]

In [ ]:
ps = PorterStemmer()

In [ ]:
[ps.stem(w) for w in words]

['play', 'play', 'happili', 'fli', 'better', 'best', 'run', 'run']

### Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
lem = WordNetLemmatizer()

In [ ]:
[lem.lemmatize(w,pos="v") for w in words]

['play', 'play', 'happily', 'fly', 'better', 'best', 'run', 'run']